# Generated by Django 5.0.3 on 2024-06-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='عنوان اندازه')),
            ],
            options={
                'verbose_name': 'اندازه',
                'verbose_name_plural': 'اندازه ها',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام مدل')),
            ],
            options={
                'verbose_name': 'نوع',
                'verbose_name_plural': 'انواع ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه دسته')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی\u200d')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
                ('children', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsets', to='product.category', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی ها ',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='تصویر محصول')),
                ('title', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('status', models.CharField(choices=[('A', 'موجود'), ('N', 'ناموجود')], max_length=1, verbose_name='وضعیت محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحی درباره محصول')),
                ('category', models.ManyToManyField(related_name='cat', to='product.category', verbose_name='دسته بندی')),
                ('size', models.ManyToManyField(related_name='supply_size', to='product.size', verbose_name='اندازه محصول')),
                ('type', models.ManyToManyField(related_name='supply_types', to='product.type', verbose_name='مدل محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_buy', models.PositiveIntegerField(verbose_name='قیمت خرید محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت فروش محصول')),
                ('inventory', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_size', to='product.size', verbose_name='سایز محصول')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_supply', to='product.supply', verbose_name='نام محصول')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_type', to='product.type', verbose_name='نوع محصول')),
            ],
            options={
                'verbose_name': 'محصول با ویژگی',
                'verbose_name_plural': ' محصولات با ویژگی',
            },
        ),
    ]
