# Generated by Django 5.0.3 on 2024-04-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_staff',
        ),
    ]
